# Generated by Django 3.1.6 on 2021-02-28 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders',
            name='IMG',
            field=models.ImageField(upload_to='uploads/', verbose_name='Изображение'),
        ),
        migrations.AlterField(
            model_name='orders',
            name='IMGAfter',
            field=models.ImageField(blank=True, upload_to='uploads/', verbose_name='Изображение после'),
        ),
        migrations.AlterField(
            model_name='orders',
            name='NameOrder',
            field=models.CharField(max_length=150, verbose_name='Наименование заказа'),
        ),
        migrations.AlterField(
            model_name='users',
            name='Email',
            field=models.EmailField(max_length=150),
        ),
    ]
